### ISSUE TITLE
Fuel burn stack don't save in world exit.

### ISSUE THREAD

**Issue by Welbre** [age-series/ElectricalAge#269]
Title says all.

**Comment by jrddunbr** [comment]
In what? Explain your testing circumstances.

**Comment by Welbre** [comment]
I think that is a NBT problem that don't save when the world close. happens every time.

**Comment by jrddunbr** [comment]
Yes, but what machines are having this problem?

**Comment by Welbre** [comment]
> Yes, but what machines are having this problem?

The fuel heat furnance.

**Comment by JollyFrankle** [comment]
![image](https://user-images.githubusercontent.com/64875622/219867909-0e0f3ddd-9134-4663-850e-af0781a030b0.png)
I also encounter this problem. Every time I load my world, every setting in my fuel heat furnaces gets reset, so I can't use it until I add them (analog regulator, fuel burner, and other settings) back. But even then, if I leave my world and load it again, it will reset again.

**Comment by jrddunbr** [comment]
Fixed in #273
