### ISSUE TITLE
Current source crashes

### ISSUE THREAD

**Issue by MsAlPatina** [age-series/ElectricalAge#284]
**version:** 1.21.2

**to replicate**:
Set Current source to something like 50A

Note: it also makes  it so you cant enter the world anymore as it crashes upon joining.

[latest.log](https://github.com/age-series/ElectricalAge/files/11951324/latest.log)
[crash-2023-07-04_17.54.23-server.txt](https://github.com/age-series/ElectricalAge/files/11951326/crash-2023-07-04_17.54.23-server.txt)

**Comment by jrddunbr** [comment]
https://github.com/age-series/ElectricalAge/blob/1.21.x/src/main/java/mods/eln/sim/process/destruct/ValueWatchdog.kt#L41

Hmm. Cute.

**Comment by jrddunbr** [comment]
What was in your circuit? Can't seem to isolate what place we are missing the configuration of the watchdog. The current source itself doesn't have a watchdog so something connected to it caused the error.

**Comment by MsAlPatina** [comment]
An closed relay, i think it was the HV one, not the high current one

**Comment by jrddunbr** [comment]
Fixed by dbb8033 (1.21.3). Uploading shortly.

**Comment by jrddunbr** [comment]
https://github.com/age-series/ElectricalAge/releases/tag/1.21.3
