### ISSUE TITLE
Crashing at starting the game

### ISSUE THREAD

**Issue by Nikolai521** [age-series/ElectricalAge#290]
I just installed minecraft from zero (1.7.10) with last version of forge, ELN works perfect with the last stable release, with the "testing" versions the game crash just at load first time

[crash-2023-07-21_19.03.59-client.txt](https://github.com/age-series/ElectricalAge/files/12130863/crash-2023-07-21_19.03.59-client.txt)

**Comment by jrddunbr** [comment]
```
Caused by: java.lang.NoClassDefFoundError: mods/eln/simplenode/energyconverter/EnergyConverterElnToOtherEntity
	at mods.eln.Eln.registerEnergyConverter(Eln.java:1028)
	at mods.eln.Eln.preInit(Eln.java:622)
```

**Comment by jrddunbr** [comment]
I've tried replicating this on 1.21.3 and I can't get it to break. Try on the new 1.21.4 version I'm about to release and tell me how it goes.

**Comment by jrddunbr** [comment]
Reopen this issue if you can replicate with this version: https://github.com/age-series/ElectricalAge/releases/tag/1.21.4

**Comment by jrddunbr** [comment]
Someone else encountered this for that version. Reopening...

In the meantime, sounds like it's some sort of shading issue with the jar so just add COFH Core and it should work. It might just be a new mod dep since the refactor.

**Comment by Nikolai521** [comment]
Ok! i tried with COFH core and the 1.21.4 ELN and it worked very well

![image](https://github.com/age-series/ElectricalAge/assets/25958695/935840f4-e768-420c-9a36-d6180487cd2c)

**Comment by Q300Z** [comment]
I've the same problem, I installed minecraft 1.7.10 from scratch with the latest version of forge 1.7.10 when i start the game it crashes.

With this error :
`The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: mods/eln/simplenode/energyconverter/EnergyConverterElnToOtherEntity`

The log :
[crash-2023-08-10_19.44.10-client.txt](https://github.com/age-series/ElectricalAge/files/12315835/crash-2023-08-10_19.44.10-client.txt)
