### ISSUE TITLE
RF or HE to Eln energy converter

### ISSUE THREAD

**Issue by TheVitya2127** [age-series/ElectricalAge#303]
Hello. Is it possible to add this converter? We would just like to use this mod for the server and yes, I understand that this is a limitation of the mod. But is it possible to add this as a new option in the mod's configuration?

**Comment by DarthSidiousPalpatine** [comment]
If you imagine RF as heat units, maybe, its easier to make that as an option.

**Comment by TheVitya2127** [comment]
I imagine it in the form of electricity from another mod

**Comment by jrddunbr** [comment]
We're not doing this, because it breaks game balance.

I suggest you find a way to convert RF or EU to steam. We accept IC2 steam and superheated steam.

**Comment by TheVitya2127** [comment]
But we have the Nuclear Tech Mod...

**Comment by TheVitya2127** [comment]
This mod has a completely different energy and fluid system. It differs from the Forge fluid system

**Comment by TheVitya2127** [comment]
IC2 will only ruin our build!

**Comment by jrddunbr** [comment]
Please feel free to create an issue for compatibility with the nuclear tech mod. That I think we can do without breaking game balance, but it may take some time before someone wants to implement it.

**Comment by jrddunbr** [comment]
(We do accept railcraft steam as well, among other Forge fluid types. Adding a non Forge fluid may be more difficult but still possible)

**Comment by TheVitya2127** [comment]
We only have Nuclear Tech Mod.  Instead of the liquid system, Forge has its own system. It cannot be converted into Eln energy
