### ISSUE TITLE
Thermal relay 

### ISSUE THREAD

**Issue by 330leon** [age-series/ElectricalAge#330]
A relay than can switch thermal energy maybe with some loss ( i mean even if the relay is open some energy passing thru for some realism)

**Comment by jrddunbr** [comment]
While technically possible, I'm not sure what it would be useful for.

**Comment by 330leon** [comment]
it could be used to add some protection to a heat power plant as a safety like to dump all heat into coolers , evry cable has his relay why not thermal?
