### ISSUE TITLE
Hope to add a computer,Camera, access control system

### ISSUE THREAD

**Issue by xxeer** [age-series/ElectricalAge#337]
To the developers, can you add computers, usable cameras, and access control systems to the mods？

Computer: can connect to the camera's view and watch, and can be connected to the access control system to control the opening and closing of doors, the switching of alarms, or the turning off of lights through the computer.

Access control system: can be connected to a computer, and can be connected to the following devices: wireless lighting control box, camera, alarm bell, or redstone chip, You can also set a password to lock the system or computer to prevent others from accessing the system.etc.

Camera: can be connected to a computer and transmit the image to the computer display via a signal line or antenna

**Comment by jrddunbr** [comment]
This is out of the scope of Electrical Age, however here's how you can do what you are asking:

1. Install [OpenComputers](https://github.com/MightyPirates/OpenComputers) or ComputerCraft.
2. Install [Computronics](https://wiki.vexatos.com/wiki:computronics)
3. Use the computronics camera and one of the computer mods to do the access control panels, etc. You can use tablets from OpenComputers to send wireless signals from your player, or you can identify the player name if you eat nanobots.
4. Use the Eln Computer Probe to control signals for the lights and other outputs.

https://wiki.electrical-age.net/index.php?title=Eln_Computer_Probe

Access control methods.
* Tablet
    * Pros: Can implement RSA or other encryption/signing to prevent someone from entering your base without a password
    * Cons: Someone can just kill you and steal the tablet
* Nanobot
    * Pros: No need to carry an item, just walk up and it shares your player's name
    * Cons: It's easy to spoof nanobots, and they are dangerous to your health (you can send commands that cause you to die to them)
    
PS. Zetta industries also has a NFC scanner that lets you do something similar.
