### ISSUE TITLE
Crash upon loading process

### ISSUE THREAD

**Issue by Tomas863** [age-series/ElectricalAge#342]
Hi, I've been trying to play with new version of the mod and none of the newest versions past the legacy ones seems to work. The crash is always the same.

The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: mods/eln/simplenode/energyconverter/EnergyConverterElnToOtherEntity

Here's the log
[crash-2024-08-04_23.06.26-client.txt](https://github.com/user-attachments/files/16489825/crash-2024-08-04_23.06.26-client.txt)

**Comment by TheBuilderBoy76** [comment]
Newer versions of ELN require COFH Core to work. Try adding that to your mods folder; it should fix the crash.

**Comment by jrddunbr** [comment]
Yep, that's the issue here.

**Comment by Tomas863** [comment]
Thanks! That did it, would be nice to have that mod included in the description to avoid any future problems

**Comment by jrddunbr** [comment]
https://github.com/age-series/ElectricalAge/releases/tag/1.21.9

The releases page has a warning about this.

**Comment by Tomas863** [comment]
It does indeed have a warning, but making it more visible, like in the CurseForge Dependencies section or on Modrinth's page, would help newcomers like me. 

Thanks for your time and help!

**Comment by jrddunbr** [comment]
https://modrinth.com/mod/electrical-age-jrddunbr-edition/version/1.21.9

I can't add it as a formal dependency, because COFH has not backfilled their older releases into the platform unfortunately.
