### ISSUE TITLE
Uhhhh shaft hubs? What are you doing?

### ISSUE THREAD

**Issue by jrddunbr** [age-series/ElectricalAge#47]
![2018-08-23_01 21 08](https://user-images.githubusercontent.com/14130505/44506119-e992e180-a672-11e8-9cb9-70985ffbf07d.png)

The renderer *thinks* that shaft is not connected but it certainly is, or the left side would already be up to speed.

To replicate: place a lot of motors and shaft hubs.

**Comment by Grissess** [comment]
Can you replicate this on the `devel-shaft-objects` tip for LLv10? If it's fixed there, this can count against the v10 milestone.

In any case, there's an interface with a default implementation to detect when connections are made on a certain side. Have you tried popping and replacing the motors on LLv9 (while shaft explosions aren't yet implemented)? To my knowledge, that callback was called under mostly correct circumstances in the v9 implementation, but any issues with v9 that I haven't noticed and explicitly correct may be causing some of the woes I have in v10.

Also try:
- Disconnecting and reconnecting; if that fixes it, it's a silly sync bug, and JointHub just needs another needPublish call, which I may have added without second thought;
- Restarting the server (or letting that happen at 4a); if that fixes it, it probably has to do with a disparity between `mergeShafts` and `rebuildNetwork`, which is something I've been fighting to reconcile in v10

A minimal reproducible build in a singleplayer instance (not necessarily a map, just instructions) would also be quite useful :)
