### ISSUE TITLE
armor sounds

### ISSUE THREAD

**Issue by jrddunbr** [age-series/ElectricalAge#70]
<lashtear> @jrddunbr: wishlist on eln armor: remove/change the damage noise/tilt when the armor absorbs
<lashtear> eg on falling
<lashtear> something unobtrusive, but clear that the armor took it instead

**Comment by jrddunbr** [comment]
If anyone has any good sounds, let me know

**Comment by OmegaHaxors** [comment]
A completely negated hit will no longer stagger you. I'll take this one on.

**Comment by jrddunbr** [comment]
This issue is being closed now since there will be no more feature updates in Electrical Age for Minecraft 1.7.10.
If the issue is relevant to 1.12, it will be re-opened there at a later date.

**Comment by jrddunbr** [comment]
Omega seems MIA.
